apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecom-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecom-web
    spec:
      containers:
      - name: ecom-web
        image: tspb80/ecom-web:v1
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "40Mi"
            cpu: "20m"
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: ecomdb
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        imagePullPolicy: Always