apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ecom-web
  namespace: ecom-app
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ecom-web