apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: ecom-app
  labels:
    app: ecom-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250M