apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.database.secretName }}

  {{- if .Values.namespace }}
  namespace: {{ .Release.Name }}-{{ .Values.namespace }}
  {{- end }}
type: Opaque
data:
  username: {{ required "dbCredentials.username is required" .Values.database.username | b64enc }}
  password: {{ required "dbCredentials.password is required" .Values.database.password | b64enc }}