name: Build and deploy Docker Image/K8s code to GKE

on:
  push:
    branches:
      - main

env:
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: chez-blue # Add your deployment name here.

jobs:
  build-image:
    name: Build and push Docker image
    runs-on:
       - ubuntu-latest
  
    steps:
    - name : Check out Git Repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:web-app"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v1

  deploy-helm:
    name: Deploy Helm charts to GKE
    runs-on:
      - ubuntu-latest
    needs: [build-image]

    steps:
    - name : Check out Git Repository
      uses: actions/checkout@v3

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
  
    - name: Authenticate to GKE without gcloud
      uses: imjasonh/gke-auth@v0.1.0
      with:
        project: ${{ secrets.GKE_PROJECT }}
        location: ${{ env.GKE_ZONE }}
        cluster:  ${{ secrets.GKE_CLUSTER }}

    - name: Deploy with Helm
      run: |
        helm upgrade ${{ env.DEPLOYMENT_NAME }} --install --set database.username=${{ secrets.DB_USERNAME }} --set database.password=${{ secrets.DB_PASSWORD }} ./helm-ecom-app/