name: Build and deploy Docker Image/K8s code to GKE

on:
  push:
    branches:
      - main

env:
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: chez-blue # Add your deployment name here.

jobs:
  build-image:
    name: Build and push Docker image
    runs-on:
       - ubuntu-latest
  
    steps:
    - name : Check out Git Repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:web-app"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v1

  deploy-helm:
    name: Deploy Helm charts to GKE
    runs-on:
      - ubuntu-latest
    needs: [build-image]

    steps:
    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
  
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: Change default gcloud project
      run: |
        gcloud config set project ${{ secrets.GKE_PROJECT }}'

    - name: Set up kubeconfig
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }}' --location ${{ env.GKE_ZONE }}
        
    - name: Deploy with Helm
      working-directory: ./helm-ecom-app
      run: |
        helm upgrade ${{ env.DEPLOYMENT_NAME }} --install .