name: Build and deploy Docker Image/K8s code to GKE

on:
  push:
    branches:
      - main

env:
  aws-production-account: ${{ secrets.AWS_PRODUCTION_ACCOUNT }}
  aws-production-bucket: ${{ secrets.AWS_PRODUCTION_BUCKET }}

jobs:
  build-image:
    runs-on:
       - ubuntu-latest
  
    steps:
    - name : Check out Git Repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:web-app"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:latest